# Generated by Django 3.2.6 on 2021-08-28 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('published', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('O', 'Ongoing')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Submitted'), ('O', 'Overdue'), ('P', 'Pending')], max_length=2)),
                ('remark', models.TextField()),
                ('submission', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
            ],
        ),
    ]
