# Generated by Django 3.2.6 on 2021-08-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_remove_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('P', 'Pending')], max_length=2),
        ),
    ]
