# Generated by Django 3.2.6 on 2021-08-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20210828_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submission',
        ),
    ]
