# Generated by Django 3.2.6 on 2021-08-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_remove_submission_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
